<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD94zYg0\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD94zYg0/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerD94zYg0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerD94zYg0\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerD94zYg0\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'D94zYg0',
    'container.build_id' => '53842e73',
    'container.build_time' => 1563663817,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD94zYg0');
