<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.app_variable' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\AppVariable.php';

$this->privates['twig.app_variable'] = $instance = new \Symfony\Bridge\Twig\AppVariable();

$instance->setEnvironment('test');
$instance->setDebug(true);
if ($this->has('security.token_storage')) {
    $instance->setTokenStorage(($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())));
}
if ($this->has('request_stack')) {
    $instance->setRequestStack(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
}

return $instance;
